### ISSUE TITLE
pkgconfig files for Windows

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/libusb-feedstock#9]
Currently the Windows build does not include a `pc` file, which makes it hard to find on Windows.

It is needed for a Windows build of ftdi (see https://github.com/conda-forge/staged-recipes/pull/14626).

**Comment by ryanvolz** [comment]
I agree that is annoying, but AFAIK upstream doesn't provide a pkgconfig file on Windows or else we would ship it. It wouldn't be too hard to provide our own... I might be able to put one together in the next few days, unless someone beats me to it.
